// flow-typed signature: bd4372a6ce9619d3ebbaf492ae51c84d
// flow-typed version: <<STUB>>/postcss-less_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-less'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-less' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-less/dist/find-extend-rule' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/find-extend-rule.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/import' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/import.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/is-mixin-token' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/is-mixin-token.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-parse' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-parse.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-parser' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-parser.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-stringifier' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-stringifier.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-stringify' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-stringify.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-syntax' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-syntax.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-tokenize' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/less-tokenize.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/rule' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/rule.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/find-end-of-escaping' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/find-end-of-escaping.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/find-end-of-expression' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/find-end-of-expression.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/globals' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/globals.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/is-escaping' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/is-escaping.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-at-rule' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-at-rule.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-backslash' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-backslash.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-basic-symbol' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-basic-symbol.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-comma' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-comma.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-default' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-default.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-inline-comment' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-inline-comment.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-multiline-comment' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-multiline-comment.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-opened-parenthesis' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-opened-parenthesis.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-quotes' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-quotes.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-symbol' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-symbol.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-whitespace' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/tokenize-whitespace.min' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/unclosed' {
  declare module.exports: any;
}

declare module 'postcss-less/dist/tokenizer/unclosed.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-less/dist/find-extend-rule.js' {
  declare module.exports: $Exports<'postcss-less/dist/find-extend-rule'>;
}
declare module 'postcss-less/dist/find-extend-rule.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/find-extend-rule.min'>;
}
declare module 'postcss-less/dist/import.js' {
  declare module.exports: $Exports<'postcss-less/dist/import'>;
}
declare module 'postcss-less/dist/import.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/import.min'>;
}
declare module 'postcss-less/dist/is-mixin-token.js' {
  declare module.exports: $Exports<'postcss-less/dist/is-mixin-token'>;
}
declare module 'postcss-less/dist/is-mixin-token.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/is-mixin-token.min'>;
}
declare module 'postcss-less/dist/less-parse.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-parse'>;
}
declare module 'postcss-less/dist/less-parse.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-parse.min'>;
}
declare module 'postcss-less/dist/less-parser.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-parser'>;
}
declare module 'postcss-less/dist/less-parser.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-parser.min'>;
}
declare module 'postcss-less/dist/less-stringifier.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-stringifier'>;
}
declare module 'postcss-less/dist/less-stringifier.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-stringifier.min'>;
}
declare module 'postcss-less/dist/less-stringify.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-stringify'>;
}
declare module 'postcss-less/dist/less-stringify.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-stringify.min'>;
}
declare module 'postcss-less/dist/less-syntax.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-syntax'>;
}
declare module 'postcss-less/dist/less-syntax.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-syntax.min'>;
}
declare module 'postcss-less/dist/less-tokenize.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-tokenize'>;
}
declare module 'postcss-less/dist/less-tokenize.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/less-tokenize.min'>;
}
declare module 'postcss-less/dist/rule.js' {
  declare module.exports: $Exports<'postcss-less/dist/rule'>;
}
declare module 'postcss-less/dist/rule.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/rule.min'>;
}
declare module 'postcss-less/dist/tokenizer/find-end-of-escaping.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/find-end-of-escaping'>;
}
declare module 'postcss-less/dist/tokenizer/find-end-of-escaping.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/find-end-of-escaping.min'>;
}
declare module 'postcss-less/dist/tokenizer/find-end-of-expression.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/find-end-of-expression'>;
}
declare module 'postcss-less/dist/tokenizer/find-end-of-expression.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/find-end-of-expression.min'>;
}
declare module 'postcss-less/dist/tokenizer/globals.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/globals'>;
}
declare module 'postcss-less/dist/tokenizer/globals.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/globals.min'>;
}
declare module 'postcss-less/dist/tokenizer/is-escaping.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/is-escaping'>;
}
declare module 'postcss-less/dist/tokenizer/is-escaping.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/is-escaping.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-at-rule.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-at-rule'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-at-rule.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-at-rule.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-backslash.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-backslash'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-backslash.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-backslash.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-basic-symbol.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-basic-symbol'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-basic-symbol.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-basic-symbol.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-comma.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-comma'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-comma.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-comma.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-default.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-default'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-default.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-default.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-inline-comment.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-inline-comment'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-inline-comment.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-inline-comment.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-multiline-comment.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-multiline-comment'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-multiline-comment.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-multiline-comment.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-opened-parenthesis.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-opened-parenthesis'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-opened-parenthesis.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-opened-parenthesis.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-quotes.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-quotes'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-quotes.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-quotes.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-symbol.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-symbol'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-symbol.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-symbol.min'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-whitespace.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-whitespace'>;
}
declare module 'postcss-less/dist/tokenizer/tokenize-whitespace.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/tokenize-whitespace.min'>;
}
declare module 'postcss-less/dist/tokenizer/unclosed.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/unclosed'>;
}
declare module 'postcss-less/dist/tokenizer/unclosed.min.js' {
  declare module.exports: $Exports<'postcss-less/dist/tokenizer/unclosed.min'>;
}
